---
title: "NLMR: Simulating neutral landscape models with R"
author: 
  - Marco Sciaini
  - Craig Eric Simpkins 
  - Kerstin Wiegand
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Neutral landscape models, originally developed as a null model against which to compare anthropogenic landscape fragmentation patterns. Today these models are mostly applied in the field of landscape ecology to test the effect of landscape patterns on spatial ecological processes. In contrast to many other ecological models (process-based, agent-based), neutral landscape models produce patterns that are not grounded in ecological reasoning. <!-- this sentence hangs a bit may need to try link it to the previous and next sentences -->

A series of such landscape patterns <!-- unclear what landscape patterns you are referring to--> can be simulated in which concerned variables are changed while other variables are kept constant. With this approach, the influence of the concerned variable on the object of study can be determined. In addition to empirical data, the simulation of landscapes with extreme configurations is possible, thus allowing one <!-- us could also be appropriate if you are ok with it --> to find thresholds for conservation related landscape processes such as fragmentation.  

So far, most of the software available to generate neutral landscapes only perform a limited set of algorithms or are implemented in programming languages that are not widely used in the field of computational ecology. Our R package aims to be a broad library of neutral landscape models that can easily be implemented in existing landscape analysis. It combines a large number of algorithms from existing software for simulating neutral landscapes, while including utility functions to classify and combine the landscapes. The simulation results are obtained in a geospatial data format (raster* objects from the raster package) and can, therefore, be used in any sort of raster data operation that is performed with standard observation data. Furthermore, the data format allows ecologists to use their simulations in most GIS software programs allowing for easy communication of their research.
