#' catalog_nlm
#'
#' @description Return a catalog of the landscape generators in NLMR.
#'
#' @details
#' The catalog is meant to help users understand the available landscape generators.
#'
#' `nlm_curds()` counts as two variants because it supports both random
#' curdling and wheyed curdling.
#'
#' @return A tibble with one row per exported landscape generator and the
#' columns `algorithm`, `group`, `description`, `variants`, and `reference`.
#'
#' @examples
#' catalog_nlm()
#'
#' @export
catalog_nlm <- function() {
  catalog <- tibble::tibble(
    algorithm = c(
      "nlm_random",
      "nlm_percolation",
      "nlm_planargradient",
      "nlm_distancegradient",
      "nlm_edgegradient",
      "nlm_mosaicfield",
      "nlm_mosaictess",
      "nlm_mosaicgibbs",
      "nlm_neigh",
      "nlm_randomcluster",
      "nlm_randomrectangularcluster",
      "nlm_mpd",
      "nlm_curds",
      "nlm_fbm",
      "nlm_gaussianfield"
    ),
    group = c(
      "random",
      "binary",
      "gradient",
      "gradient",
      "gradient",
      "tessellation",
      "tessellation",
      "tessellation",
      "categorical",
      "cluster",
      "cluster",
      "fractal",
      "curdling",
      "fractal",
      "correlated field"
    ),
    description = c(
      "Independent random values drawn for each cell.",
      "Binary landscapes from thresholded random draws.",
      "Linear gradients in a specified or random direction.",
      "Distance gradients measured from a rectangular origin.",
      "Directional gradients with a central peak.",
      "Mosaic random fields generated by repeated bisection.",
      "Voronoi tessellations from random seed points.",
      "Inhibited point-pattern tessellations.",
      "Categorical landscapes shaped by neighbourhood effects.",
      "Nearest-neighbour random clusters.",
      "Overlapping rectangular clusters.",
      "Midpoint displacement surfaces.",
      "Recursive curdling with optional wheying.",
      "Fractional Brownian motion surfaces.",
      "Spatially correlated Gaussian random fields."
    ),
    variants = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L),
    reference = c(
      "With and Crist (1995)",
      "Gardner et al. (1989)",
      "Palmer (1992)",
      "Etherington, Holland, and O'Sullivan (2015)",
      "Travis and Dytham (2004); Schlather et al. (2015)",
      "Schlather et al. (2015)",
      "Gaucherel (2008), Method 1",
      "Gaucherel (2008), Method 2",
      "Scherer et al. (2016)",
      "Saura and Martinez-Millan (2000)",
      "Gustafson and Parker (1992)",
      "Peitgen and Saupe (1988)",
      "O'Neill, Gardner, and Turner (1992); Keitt (2000)",
      "Schlather et al. (2015)",
      "Schlather et al. (2015)"
    )
  )

  catalog[order(catalog$group, catalog$algorithm), , drop = FALSE]
}
