#' nlm_perlinnoise
#'
#' @description Simulates a two-dimensional Perlin-noise neutral landscape model.
#'
#' @details
#' Perlin noise is generated by summing smooth gradient-noise layers (octaves).
#' Each successive layer changes spatial frequency by `lacunarity` and amplitude
#' by `persistence`.
#'
#' @param ncol [\code{numerical(1)}]\cr Number of columns forming the raster.
#' @param nrow [\code{numerical(1)}]\cr Number of rows forming the raster.
#' @param resolution [\code{numerical(1)}]\cr Resolution of the raster.
#' @param periods [\code{numerical(1:2)}]\cr Number of vertical and horizontal periods in the first octave, following the row-column convention used by Etherington (2022).
#' @param octaves [\code{integer(1)}]\cr Number of noise layers to combine.
#' @param lacunarity [\code{numerical(1)}]\cr Frequency multiplier between octaves.
#' @param persistence [\code{numerical(1)}]\cr Amplitude multiplier between octaves.
#' @param user_seed [\code{numerical(1)}]\cr Set random seed for the simulation.
#' @param rescale [\code{logical(1)}]\cr If `TRUE` (default), rescale values to 0--1.
#'
#' @return A `SpatRaster`.
#'
#' @references Etherington, T. R. (2022). Perlin noise as a hierarchical
#' neutral landscape model. Web Ecology, 22, 1--6.
#' \url{https://doi.org/10.5194/we-22-1-2022}
#'
#' @examples
#' perlin <- nlm_perlinnoise(ncol = 80, nrow = 80, periods = 4)
#'
#' @export
nlm_perlinnoise <- function(ncol,
                            nrow,
                            resolution = 1,
                            periods = 4,
                            octaves = 3,
                            lacunarity = 2,
                            persistence = 0.5,
                            user_seed = NULL,
                            rescale = TRUE) {
  checkmate::assert_count(ncol, positive = TRUE)
  checkmate::assert_count(nrow, positive = TRUE)
  checkmate::assert_number(resolution, lower = 0)
  checkmate::assert_numeric(periods, lower = 1)
  checkmate::assert_true(length(periods) %in% 1:2)
  periods <- rep(periods, length.out = 2)
  checkmate::assert_count(octaves, positive = TRUE)
  checkmate::assert_number(lacunarity, lower = 1)
  checkmate::assert_number(persistence, lower = 0, upper = 1)
  checkmate::assert_integerish(user_seed, len = 1, lower = 1, null.ok = TRUE)
  checkmate::assert_logical(rescale, len = 1)

  if (!is.null(user_seed)) {
    set.seed(as.integer(user_seed))
  }

  noise <- matrix(0, nrow = nrow, ncol = ncol)
  amplitude <- 1
  amplitude_sum <- 0
  frequency <- periods

  for (i in seq_len(octaves)) {
    noise <- noise + amplitude * perlin_octave(nrow, ncol, frequency[2], frequency[1])
    amplitude_sum <- amplitude_sum + amplitude
    frequency <- frequency * lacunarity
    amplitude <- amplitude * persistence
  }

  noise <- noise / amplitude_sum
  out <- terra::rast(noise)
  terra::ext(out) <- c(0, ncol * resolution, 0, nrow * resolution)

  if (rescale) {
    out <- util_rescale(out)
  }

  util_update_metadata(out)
}

perlin_octave <- function(nrow, ncol, periods_x, periods_y) {
  nx <- ceiling(periods_x) + 1L
  ny <- ceiling(periods_y) + 1L
  gradients <- matrix(stats::runif(nx * ny * 2L, -1, 1), nrow = nx * ny, ncol = 2)
  gradients <- gradients / sqrt(rowSums(gradients^2))
  gradients <- array(gradients, dim = c(nx, ny, 2L))

  x <- seq(0, periods_x, length.out = ncol)
  y <- seq(0, periods_y, length.out = nrow)
  ix <- pmin(floor(x) + 1L, nx - 1L)
  iy <- pmin(floor(y) + 1L, ny - 1L)
  fx <- x - floor(x)
  fy <- y - floor(y)
  sx <- perlin_fade(fx)
  sy <- perlin_fade(fy)

  out <- matrix(0, nrow = nrow, ncol = ncol)
  for (r in seq_len(nrow)) {
    for (c in seq_len(ncol)) {
      gx <- ix[c]
      gy <- iy[r]
      dx <- fx[c]
      dy <- fy[r]
      n00 <- dx * gradients[gx, gy, 1] + dy * gradients[gx, gy, 2]
      n10 <- (dx - 1) * gradients[gx + 1, gy, 1] + dy * gradients[gx + 1, gy, 2]
      n01 <- dx * gradients[gx, gy + 1, 1] + (dy - 1) * gradients[gx, gy + 1, 2]
      n11 <- (dx - 1) * gradients[gx + 1, gy + 1, 1] + (dy - 1) * gradients[gx + 1, gy + 1, 2]
      nx0 <- n00 + sx[c] * (n10 - n00)
      nx1 <- n01 + sx[c] * (n11 - n01)
      out[r, c] <- nx0 + sy[r] * (nx1 - nx0)
    }
  }
  out
}

perlin_fade <- function(x) {
  x^3 * (x * (x * 6 - 15) + 10)
}
