# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_mpd <- function(ncol, nrow, rand_dev, roughness_vec) {
    .Call('_NLMR_rcpp_mpd', PACKAGE = 'NLMR', ncol, nrow, rand_dev, roughness_vec)
}

#' @export
rcpp_randomrectangularcluster <- function(ncol, nrow, minl, maxl) {
    .Call('_NLMR_rcpp_randomrectangularcluster', PACKAGE = 'NLMR', ncol, nrow, minl, maxl)
}

