# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_mpd <- function(ncol, nrow, rand_dev, rcpp_roughness) {
    .Call('_NLMR_rcpp_mpd', PACKAGE = 'NLMR', ncol, nrow, rand_dev, rcpp_roughness)
}

rcpp_neigh <- function(nrow, ncol, mat, n_categories, cells_per_cat, neighbourhood, p_neigh, p_empty) {
    .Call('_NLMR_rcpp_neigh', PACKAGE = 'NLMR', nrow, ncol, mat, n_categories, cells_per_cat, neighbourhood, p_neigh, p_empty)
}

rcpp_randomrectangularcluster <- function(ncol, nrow, minl, maxl) {
    .Call('_NLMR_rcpp_randomrectangularcluster', PACKAGE = 'NLMR', ncol, nrow, minl, maxl)
}

