#' util_rescale
#'
#' Linearly rescale element values in a raster to a range between 0 and 1
#'
#' @param x [\code{Raster* object} or \code{SpatRaster}]
#'
#' @return Raster* object or \code{SpatRaster} with values ranging from 0-1
#'
#' @details Rasters generated by \code{nlm_*} functions are scaled between 0 and 1 as default, this option can be set to \code{FALSE} if needed.
#'
#' @keywords internal
#'

util_rescale <- function(x) {
  raster_input <- inherits(x, c("RasterLayer", "RasterBrick", "RasterStack", "Raster"))
  x_spat <- if (raster_input) terra::rast(x) else x

  stats <- terra::global(x_spat, c("min", "max"), na.rm = TRUE)
  min_value <- stats[1, "min"]
  max_value <- stats[1, "max"]

  rescaled_spat <-
    (x_spat - min_value) /
    (max_value - min_value)

  if (raster_input) {
    if (terra::nlyr(rescaled_spat) > 1) {
      return(raster::brick(rescaled_spat))
    }
    return(raster::raster(rescaled_spat))
  }

  return(rescaled_spat)
}
