#' util_rescale
#'
#' Linearly rescale element values in a raster to a range between 0 and 1
#'
#' @param r [\code{Raster* object}]
#'
#' @return Raster* object with values ranging from 0-1
#'
#' @details Rasters generated by \code{nlm_} functions are scaled between 0 and 1 as default, this option can be set to \code{FALSE} if needed.
#'
#' @examples
#'
#' util_rescale(nlm_random(10, 10,  rescale = FALSE))
#'
#'
#' @aliases util_rescale
#' @rdname util_rescale
#'
#' @export
#'

util_rescale <- function(r) {
    rescaled_NLM <-
      (r - raster::cellStats(r, "min")) /
                   (raster::cellStats(r, "max") - raster::cellStats(r, "min"))

    return(rescaled_NLM)


  }
