#' util_rescale
#'
#' Linearly rescale element values in a raster to a range between 0 and 1
#'
#' @param x [\code{SpatRaster}]
#'
#' @return \code{SpatRaster} with values ranging from 0-1
#'
#' @details Rasters generated by \code{nlm_*} functions are scaled between 0 and 1 as default, this option can be set to \code{FALSE} if needed.
#'
#' @keywords internal
#'

util_rescale <- function(x) {
  if (!inherits(x, "SpatRaster")) {
    stop("x must be a SpatRaster.")
  }

  stats <- terra::global(x, c("min", "max"), na.rm = TRUE)
  min_value <- stats[1, "min"]
  max_value <- stats[1, "max"]

  if (isTRUE(all.equal(min_value, max_value))) {
    out <- terra::setValues(x, 0)
    return(out)
  }

  (x - min_value) /
    (max_value - min_value)
}
